### ISSUE TITLE
iD Editor (gothamjs)

### ISSUE THREAD

**Issue by tmcw** [tmcw/presentations#7]
- [ ] Final slide (thanks)
- [ ] Data model notes

**Comment by pgiraud** [comment]
http://macwright.org/presentations/gotham-2/#15
"midpoints"? Did you mean "lines"?

**Comment by pgiraud** [comment]
http://macwright.org/presentations/gotham-2/#20

You may want to show the next step which is (if my understanding is correct):

```
// a component
function choice(msg) {
  // an event emitter
  var event = d3.dispatch('click');

  function choice(selection) {
    // the meat
    selection.append('a').text(msg)
      .on('click', function() {
        event.click(msg);
      });
  }
  // simple composition
  return d3.rebind(choice, event, 'on');
}
```

**Comment by tmcw** [comment]
Cool, should be fixed. Thanks for the notes @pgiraud !
